name: hymt
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.1.80
  - cuda-runtime=12.1.0
  - cuda-version=13.1
  - dav1d=1.2.1
  - expat=2.7.3
  - filelock=3.20.2
  - fsspec=2025.12.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - jinja2=3.1.6
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240722.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.16.0.49
  - libcurand=10.4.1.34
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libheif=1.19.7
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=5.28.3
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.3
  - openssl=3.6.0
  - pillow=11.3.0
  - pip=25.3
  - pthread-stubs=0.3
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch-mutex=1.0
  - rav1e=0.7.1
  - readline=8.3
  - setuptools=80.9.0
  - sleef=3.9.0
  - sqlite=3.51.0
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - modelscope==1.33.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - protobuf==6.33.2
      - psutil==7.2.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - starlette==0.50.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.56.0
      - triton==3.5.1
      - typer-slim==0.21.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /home/lystran/Applications/miniconda/envs/hymt
